Deck/urls.py
from django.urls import path
from .views import agregar_deck, eliminar_deck, ver_flashcards, agregar_flashcard, eliminar_flashcard, estudiar_deck, terminar_estudio


app_name = 'Deck'

urlpatterns = [
    path('add/', agregar_deck, name='agregar_deck'),
    path('delete/<int:deck_id>/', eliminar_deck, name='eliminar_deck'),
    path('<int:deck_id>/flashcards/', ver_flashcards, name='ver_flashcards'),
    path('<int:deck_id>/flashcards/add/',
         agregar_flashcard, name='agregar_flashcard'),
    path('<int:deck_id>/flashcards/delete/<int:flashcard_id>/',
         eliminar_flashcard, name='eliminar_flashcard'),
    path('<int:deck_id>/flashcards/estudiar/',
         estudiar_deck, name='estudiar_deck'),
    path('<int:deck_id>/flashcards/estudiar/terminar/',
         terminar_estudio, name='terminar_estudio'),

]

sistema_de_estudio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('usuario.urls')),
    path("Deck/", include('Deck.urls')),
]

usuario/urls.py
from django.urls import path
from .views import user_login, user_registration, home, logout_view, como_funciona_view

app_name = 'usuario'

urlpatterns = [
    path('', home, name='home'),
    path('login/', user_login, name='login'),
    path('register/', user_registration, name='register'),
    path('logout/', logout_view, name='logout'),
    path('como_funciona/', como_funciona_view, name='como_funciona'),
]

usuario/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    pass

# Form para realizar el registro del usuario


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields

usuario/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegistrationForm
from Deck.forms import DeckForm
from Deck.models import Deck
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Devuelve la vista a la página principal de la aplicación
def home(request):
    context = {}
    context['form'] = DeckForm()

    # Si existen mensajes de sesión los obtenemos
    mensajes = messages.get_messages(request)

    # Separamos los mensajes de éxito y los de fallo
    context['mensajes_exito'] = []
    context['mensajes_fallo'] = []
    for mensaje in mensajes:
        if mensaje.tags == 'success':
            context['mensajes_exito'].append(mensaje)
        else:
            context['mensajes_fallo'].append(mensaje)

    # Si el usuario está autenticado extraemos todos sus Decks
    context['decks'] = {}
    if request.user.is_authenticated:
        context['decks'] = Deck.objects.filter(usuario=request.user)

    return render(request, 'usuario/index.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request, request.POST)
        if form.is_valid():
            # Hacemos el Login
            user = authenticate(
                request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            login(request, user)
            return redirect('usuario:home')  # Redirige a la página principal
    else:
        form = UserLoginForm()

    return render(request, 'usuario/login.html', {'form': form})


def user_registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            # Registramos al usuario y lo enviamos al Login
            form.save()
            return redirect('usuario:login')  # Redirige a la página de Login
    else:
        form = UserRegistrationForm()

    return render(request, 'usuario/register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('usuario:home')


@login_required
def como_funciona_view(request):
    return render(request, 'usuario/como_funciona.html')

usuario/templates/usuario/como_funciona.html
{% extends 'base.html' %}

{% block title %}¿Cómo funciona?{% endblock %}

{% block content %}
    <div class="container m-3">
        <h2 class="fs-2">Propósito del sistema</h2>
        <p class="fs-5">Esta aplicación proporciona una herramienta eficaz para estudiar cualquier tema. Su funcionamiento se basa en el uso de "Decks" (conjuntos de tarjetas) y "Flashcards" (tarjetas de pregunta y respuesta). Estas tarjetas permiten organizar y revisar el contenido de manera estructurada, facilitando así el proceso de aprendizaje.</p>
        <br>
        <h2 class="fs-2">¿Cómo funciona?</h2>
        <ol>
            <li class="fs-5">Comienza creando tu cuenta e iniciando sesión en el sistema.</li>
            <li class="fs-5">Crea un nuevo conjunto de tarjetas (Deck).</li>
            <li class="fs-5">Asocia tarjetas de pregunta y respuesta (Flashcards) al conjunto.</li>
            <li class="fs-5">¡Listo! Inicia tu estudio y repasa los conceptos fundamentales para mejorar tu aprendizaje.</li>
        </ol>
    </div>
{% endblock %}

usuario/templates/usuario/index.html
{% extends 'base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}

    {% if request.user.is_authenticated %}
        <div class="container mt-2">
            <h1>Decks</h1>

            {% if mensajes_exito %}
                {% for mensaje in mensajes_exito %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ mensaje }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}

            {% if mensajes_fallo %}
                {% for mensaje in mensajes_fallo %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ mensaje }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}

            <!-- Tabla donde se muestran los Decks del usuario -->
            <table class="table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Nombre del Deck</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for deck in decks %}
                            <tr>
                                <td><strong>{{ deck.nombre }}</strong></td>
                                <td>
                                    <a href="{% url 'Deck:ver_flashcards' deck.id %}" class="btn btn-primary">Ver</a>
                                    <a href="{% url 'Deck:eliminar_deck' deck.id %}" class="btn btn-danger">Eliminar</a>
                                    <a href="{% url 'Deck:estudiar_deck' deck.id %}" class="btn btn-secondary">Estudiar Deck</a>
                                </td>
                            </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="col-12 text-center mt-2">
                <!-- Boton para crear un nuevo Deck -->
                <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#creardeck">
                    + Agregar un nuevo Deck
                </button>
            </div>  
        
            <!-- Modal para crear un nuevo Deck -->
            <div class="modal fade" id="creardeck" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Crear nuevo Deck</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{% url 'Deck:agregar_deck' %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary">Crear</button>
                        </form>
                    </div>
                    
                </div>
                </div>
            </div>

        </div>
    
        {% else %}
            <div class="container m-3">
                <h2 class="fs-2">Propósito del sistema</h2>
                <p class="fs-5">Esta aplicación proporciona una herramienta eficaz para estudiar cualquier tema. Su funcionamiento se basa en el uso de "Decks" (conjuntos de tarjetas) y "Flashcards" (tarjetas de pregunta y respuesta). Estas tarjetas permiten organizar y revisar el contenido de manera estructurada, facilitando así el proceso de aprendizaje.</p>
                <br>
                <h2 class="fs-2">¿Cómo funciona?</h2>
                <ol>
                    <li class="fs-5">Comienza creando tu cuenta e iniciando sesión en el sistema.</li>
                    <li class="fs-5">Crea un nuevo conjunto de tarjetas (Deck).</li>
                    <li class="fs-5">Asocia tarjetas de pregunta y respuesta (Flashcards) al conjunto.</li>
                    <li class="fs-5">¡Listo! Inicia tu estudio y repasa los conceptos fundamentales para mejorar tu aprendizaje.</li>
                </ol>
            </div>
        {% endif %}

{% endblock %}

usuario/templates/usuario/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

    <div class="container mt-5">
        <form method="post"  style="width: 500px; margin: 0 auto;" action="{% url 'usuario:login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="display: flex;justify-content: space-between;align-items: center;">
                <button type="submit" class="btn btn-primary">Iniciar sesión</button>
                <a href="{% url 'usuario:register' %}">¿Aún no tienes una cuenta?</a>
            </div>
        </form> 
    </div>

    <!-- Script para agregar estilos -->
    <script>
        usernameInput = document.getElementById("id_username");
        usernameInput.classList.add("form-control");
    
        passwordInput = document.getElementById("id_password");
        passwordInput.classList.add("form-control");
    </script>
{% endblock %}

usuario/templates/usuario/register.html
{% extends 'base.html' %}

{% block title %}Registro{% endblock %}

{% block content %}

    <div class="container mt-5">
        <form method="post" style="width: 500px; margin: 0 auto;" action="{% url 'usuario:register' %}">
            {% csrf_token %}
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.username.errors  }}
            <br>

            {{ form.password1.label_tag }}
            {{ form.password1 }}
            {{ form.password1.errors }}
            <br>

            {{ form.password2.label_tag }}
            {{ form.password2 }}
            {{ form.password2.errors }}
            <br>
            
            <button type="submit" class="btn btn-primary">Registrarse</button>
        </form>
    </div>

    <!-- Script para agregar estilos -->
    <script>
        usernameInput = document.getElementById("id_username");
        usernameInput.classList.add("form-control");
    
        password1Input = document.getElementById("id_password1");
        password1Input.classList.add("form-control");
    
        password2Input = document.getElementById("id_password2");
        password2Input.classList.add("form-control");
    </script>

{% endblock %}