Deck/urls.py
from django.urls import path
from .views import agregar_deck, eliminar_deck, ver_flashcards, agregar_flashcard, eliminar_flashcard, estudiar_deck, terminar_estudio


app_name = 'Deck'

urlpatterns = [
    path('add/', agregar_deck, name='agregar_deck'),
    path('delete/<int:deck_id>/', eliminar_deck, name='eliminar_deck'),
    path('<int:deck_id>/flashcards/', ver_flashcards, name='ver_flashcards'),
    path('<int:deck_id>/flashcards/add/',
         agregar_flashcard, name='agregar_flashcard'),
    path('<int:deck_id>/flashcards/delete/<int:flashcard_id>/',
         eliminar_flashcard, name='eliminar_flashcard'),
    path('<int:deck_id>/flashcards/estudiar/',
         estudiar_deck, name='estudiar_deck'),
    path('<int:deck_id>/flashcards/estudiar/terminar/',
         terminar_estudio, name='terminar_estudio'),

]

sistema_de_estudio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('usuario.urls')),
    path("Deck/", include('Deck.urls')),
]

usuario/urls.py
from django.urls import path
from .views import user_login, user_registration, home, logout_view, como_funciona_view

app_name = 'usuario'

urlpatterns = [
    path('', home, name='home'),
    path('login/', user_login, name='login'),
    path('register/', user_registration, name='register'),
    path('logout/', logout_view, name='logout'),
    path('como_funciona/', como_funciona_view, name='como_funciona'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Título por defecto{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

    <!-- Barra de navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" style="font-weight: bold;" href="{% url 'usuario:home' %}">APP NAME</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'usuario:home' %}">Home</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'usuario:como_funciona' %}">Como funciona</a>
                </li>
              {% endif %}
            </ul>
            <span class="navbar-text">
                {% if not request.user.is_authenticated %}
                    <a href="{% url 'usuario:register' %}" class="btn btn-secondary">Registrarte</a>
                    <a href="{% url 'usuario:login' %}" class="btn btn-info">Login</a>
                {% else %}
                    <p style="display: inline-block;color: aliceblue;font-weight: bold;">{{ request.user.username }}</p>
                    <a href="{% url 'usuario:logout' %}" class="btn btn-secondary">Cerrar sesión</a>
                {% endif %}
            </span>
          </div>
        </div>
    </nav>

    <main>
      {% block content %}{% endblock %}
    </main>
    
</body>
</html>