Deck/urls.py
from django.urls import path
from .views import agregar_deck, eliminar_deck, ver_flashcards, agregar_flashcard, eliminar_flashcard, estudiar_deck, terminar_estudio


app_name = 'Deck'

urlpatterns = [
    path('add/', agregar_deck, name='agregar_deck'),
    path('delete/<int:deck_id>/', eliminar_deck, name='eliminar_deck'),
    path('<int:deck_id>/flashcards/', ver_flashcards, name='ver_flashcards'),
    path('<int:deck_id>/flashcards/add/',
         agregar_flashcard, name='agregar_flashcard'),
    path('<int:deck_id>/flashcards/delete/<int:flashcard_id>/',
         eliminar_flashcard, name='eliminar_flashcard'),
    path('<int:deck_id>/flashcards/estudiar/',
         estudiar_deck, name='estudiar_deck'),
    path('<int:deck_id>/flashcards/estudiar/terminar/',
         terminar_estudio, name='terminar_estudio'),

]

sistema_de_estudio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('usuario.urls')),
    path("Deck/", include('Deck.urls')),
]

Deck/models.py
from django.db import models
from django.contrib.auth.models import User


class Deck(models.Model):
    nombre = models.CharField(max_length=100)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nombre


class FlashCard(models.Model):
    parte_frontal = models.TextField()
    parte_trasera = models.TextField()
    deck = models.ForeignKey(
        Deck, on_delete=models.CASCADE, related_name='flashcards')

    def __str__(self):
        return f'{self.parte_frontal} - {self.parte_trasera}'

Deck/forms.py
from django import forms
from .models import Deck, FlashCard


class DeckForm(forms.ModelForm):
    class Meta:
        model = Deck
        fields = ['nombre']

        widgets = {
            "nombre": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Ingrese el nombre del nuevo Deck",
                }
            ),
            "usuario": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Ingrese el nombre del nuevo Deck",
                }
            ),
        }


class FlashCardForm(forms.ModelForm):
    class Meta:
        model = FlashCard
        fields = ['parte_frontal', 'parte_trasera']

        widgets = {
            "parte_frontal": forms.Textarea(
                attrs={
                    "class": "form-control",
                }
            ),
            "parte_trasera": forms.Textarea(
                attrs={
                    "class": "form-control",
                }
            ),
        }

Deck/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import DeckForm, FlashCardForm
from django.shortcuts import redirect
from .models import Deck, FlashCard
from django.contrib import messages
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def agregar_deck(request):
    if request.method == 'POST':
        form = DeckForm(request.POST)
        form.instance.usuario = request.user
        if form.is_valid():
            form.save()
            messages.success(request, 'Se ha creado el Deck exitosamente!')
        else:
            messages.error(
                request, 'No se pudo crear el Deck. Asegurate de ingresar datos correctos.')
    else:
        messages.error(request, 'Método inválido')

    return redirect('usuario:home')  # Redirige a la página principal


@login_required
def eliminar_deck(request, deck_id):
    # Válido que el Deck que se quiere eliminar sea del usuario que lo creo, es decir, un usuario no puede eliminar
    # un Deck que no le pertenezca.
    deck = Deck.objects.filter(usuario=request.user, id=deck_id)
    if deck.exists():
        # Borramos el Deck
        deck.delete()
        messages.success(request, 'Se ha eliminado el Deck!')
    else:
        messages.error(request, 'Acción no permitida')

    return redirect('usuario:home')  # Redirige a la página principal

# Esta vista muestra las FlashCards de un Deck en específico


@login_required
def ver_flashcards(request, deck_id):
    # Válido que el usuario que quiere ver las FlashCards del Deck sea el dueño del Deck.
    deck = get_object_or_404(Deck, id=deck_id, usuario=request.user)

    # Obtengo las FlashCards del Deck
    context = {}
    context['flashcards'] = FlashCard.objects.filter(deck=deck)
    context['deck'] = deck
    context['form'] = FlashCardForm()
    return render(request, 'Deck/CRUD_flashcards.html', context)


@login_required
def agregar_flashcard(request, deck_id):
    if request.method == 'POST':
        # Válido que la FlashCard que quiere agregar el usuario sea para un Deck del cual el usuario es el dueño
        deck = get_object_or_404(Deck, id=deck_id, usuario=request.user)

        # Agrego la FlashCard al Deck
        form = FlashCardForm(request.POST)
        form.instance.deck = deck
        if form.is_valid():
            form.save()
    # Redirige a la vista para ver las FlashCards
    url_destino = reverse('Deck:ver_flashcards', kwargs={'deck_id': deck.id})
    return redirect(url_destino)


@login_required
def eliminar_flashcard(request, deck_id, flashcard_id):
    # Valido que el Deck sea del usuario
    deck = get_object_or_404(Deck, id=deck_id, usuario=request.user)

    # Eliminamos la FlashCard
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    flashcard.delete()

    # Redirige a la vista para ver las FlashCards
    url_destino = reverse('Deck:ver_flashcards', kwargs={'deck_id': deck_id})
    return redirect(url_destino)

# Permite que el usuario pueda estudiar un Deck


@login_required
def estudiar_deck(request, deck_id):
    # Verifico que el deck que se quiere estudiar le pertenezca al usuario que lo quiere estudiar
    deck = get_object_or_404(Deck, id=deck_id, usuario=request.user)

    # Obtengo todas las flashcards del deck
    flashcards = FlashCard.objects.filter(deck=deck)

    # Creo una paginiación para estudiar el deck
    paginator = Paginator(flashcards, 1)

    # Se obtiene el número de flashcard de la solicitud GET, o 1 si no está presente
    pagina = request.GET.get('pagina', 1)

    try:
        flashcard_objects = paginator.page(pagina)
    except PageNotAnInteger:
        # Si la flashcard no es un número entero, muestra la primera flashcard
        flashcard_objects = paginator.page(1)
    except EmptyPage:
        # Si la flashcard está fuera de rango (por encima del número total de flashcards),
        # muestra la última flashcards disponible
        flashcard_objects = paginator.page(paginator.num_pages)

    context = {}
    context['deck'] = deck
    context['flashcard_objects'] = flashcard_objects
    return render(request, 'Deck/estudiar_deck.html', context)


# Esta vista termina el estudio del Deck y redirige a la vista que lista las FlashCards
@login_required
def terminar_estudio(request, deck_id):
    # Valido que al Deck que se vaya a redirigir sea un Deck del cual el usuario sea el dueño
    deck = get_object_or_404(Deck, id=deck_id, usuario=request.user)

    # Redirige a la vista para ver las FlashCards
    url_destino = reverse('Deck:ver_flashcards', kwargs={'deck_id': deck.id})
    return redirect(url_destino)

Deck/templates/Deck/CRUD_flashcards.html
{% extends 'base.html' %}

{% block title %}FlashCards{% endblock %}

{% block content %}

    <div class="container mt-3">

        <h1>Deck: {{ deck.nombre }}</h1>

        <!-- Tabla donde se muestran las flashCards de un Deck -->
        <table class="table">
            <thead class="table-light">
                <tr>
                    <th scope="col">Parte frontal</th>
                    <th scope="col">Parte tracera</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for flashcard in flashcards %}
                        <tr>
                            <td>{{ flashcard.parte_frontal }}</td>
                            <td>{{ flashcard.parte_trasera }}</td>
                            <td> <a href="{% url 'Deck:eliminar_flashcard' deck.id flashcard.id %}" class="btn btn-danger">Eliminar</a> </td>
                        </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="col-12 text-center mt-2">
            <!-- Botón para crear una nueva Flashcard -->
            <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#crearflashcard">
                + Agregar una nueva flashcard
            </button>
        </div>

        <!-- Modal para crear nuevas Flashcards -->
        <div class="modal fade" id="crearflashcard" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Crear nuevo Deck</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                   <form method="post" action="{% url 'Deck:agregar_flashcard' deck.id  %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Crear</button>
                   </form>
                </div>
                
            </div>
            </div>
        </div>

    </div>
{% endblock %}

Deck/templates/Deck/estudiar_deck.html
{% extends 'base.html' %}

{% block title %}Estudiar Deck{% endblock %}

{% block content %}

    <div class="container mt-5" style="padding: 30px;background-color: #BAC9D6;">

        <div class="col-12 text-center mt-2">
            <a href="{% url 'Deck:terminar_estudio' deck.id %}" class="btn btn-danger" >Terminar</a>
            <br>
            <h5 class="current">
                Flashcard {{ flashcard_objects.number }} de {{ flashcard_objects.paginator.num_pages }}.
            </h5>
        </div>

        {% for flashcard in flashcard_objects %}
            <div class="col-12 text-center mt-2">
                <h4>{{ flashcard.parte_frontal }}</h4>
            </div>
            <div class="col-12 text-center mt-5">
                <h4 style="display: none;" id="respuesta">{{ flashcard.parte_trasera }}</h4>
            </div>
        {% endfor %}

        <div class="col-12 text-center mt-5" style="display: flex; justify-content: space-between;">
            {% if flashcard_objects.has_previous %}
                <a href="?pagina={{ flashcard_objects.previous_page_number }}" class="btn btn-primary"> Anterior</a>
            {% endif %}
            
            <button href="" class="btn btn-secondary" id="btnMostrarRespuesta">Mostrar respuesta</button>

            {% if flashcard_objects.has_next %}
                <a href="?pagina={{ flashcard_objects.next_page_number }}" class="btn btn-primary">Siguiente </a>
            {% endif %}
        </div>
    </div>

    <script>
        btnMostrarRespuesta = document.getElementById("btnMostrarRespuesta");
        btnMostrarRespuesta.addEventListener("click",function(){
            respuesta = document.getElementById("respuesta");
            respuesta.style.display = "inline";
        });
    </script>

{% endblock %}